enableGlobalCache: false

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v3.0.0/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.6.cjs
